using System;
using System.IO;
using System.Text;
using Polsys.Ref.Models;

namespace Polsys.Ref.Export
{
    /// <summary>
    /// Exports the catalogue to a Word XML bibliography file.
    /// </summary>
    internal class WordExporter: CatalogueExporter
    {
        public override string FileExtension
        {
            get
            {
                return "xml";
            }
        }

        public override string Name
        {
            get
            {
                return "Microsoft Word sources";
            }
        }

        public override bool Export(Stream stream, Catalogue catalogue)
        {
            using (var writer = new StreamWriter(stream, Encoding.UTF8, 1024, true))
            {
                // Start the XML document and the source collection
                writer.Write("<?xml version=\"1.0\"?>");
                writer.Write("<!-- Generated by Ref " + GetVersionString() + " at " + DateTime.Now.ToString() + ". -->");
                writer.Write("<b:Sources SelectedStyle=\"\" xmlns:b=\"http://schemas.openxmlformats.org/officeDocument/2006/bibliography\" " +
                    "xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/bibliography\">");

                // Write each entry
                foreach (var entry in catalogue.Entries)
                {
                    if (entry is Article)
                        WriteArticle((Article)entry, writer);
                }

                // End the collection
                writer.Write("</b:Sources>");
            }

            return true;
        }

        internal void WriteArticle(Article article, TextWriter writer)
        {
            writer.Write("<b:Source>");
            writer.Write("<b:SourceType>JournalArticle</b:SourceType>");
            WriteRandomGuid(writer);

            WriteNonEmptyElement("b:Tag", article.Key, writer);
            WriteNonEmptyElement("b:DOI", article.Doi, writer);
            WriteNonEmptyElement("b:StandardNumber", article.Issn, writer);
            WriteNonEmptyElement("b:JournalName", article.Journal, writer);
            WriteNonEmptyElement("b:Issue", article.Number, writer);
            WriteNonEmptyElement("b:Pages", article.PageRange, writer);
            WriteNonEmptyElement("b:Title", article.Title, writer);
            WriteNonEmptyElement("b:Volume", article.Volume, writer);
            WriteNonEmptyElement("b:Year", article.Year, writer);
            
            if (!string.IsNullOrEmpty(article.Author))
            {
                writer.Write("<b:Author><b:Author>");
                WriteNameList(article.Author, writer);
                writer.Write("</b:Author></b:Author>");
            }

            writer.Write("</b:Source>");
        }

        internal static void WriteNameList(string authorString, TextWriter writer)
        {
            // TODO: Middle names are not used, but Word supports them.
            writer.Write("<b:NameList>");
            
            var names = authorString == null ? new string[0] : authorString.Split(';');
            foreach (var name in names)
            {
                if (string.IsNullOrEmpty(name))
                    continue;

                // Parse the name in either "Last, First", "First Last" or "Name" convention
                string lastName = string.Empty;
                string firstName = string.Empty;
                if (name.Contains(","))
                {
                    var splitIndex = name.IndexOf(',');
                    lastName = name.Substring(0, splitIndex).Trim();
                    firstName = name.Substring(splitIndex + 1, name.Length - splitIndex - 1).Trim();
                }
                else
                {
                    var trimmedName = name.Trim();
                    var splitIndex = trimmedName.LastIndexOf(' '); // Only consider the last token the last name
                    if (splitIndex == -1)
                    {
                        lastName = trimmedName;
                    }
                    else
                    {
                        firstName = trimmedName.Substring(0, splitIndex).Trim();
                        lastName = trimmedName.Substring(splitIndex + 1, trimmedName.Length - splitIndex - 1).Trim();
                    }
                }

                writer.Write("<b:Person>");
                if (!string.IsNullOrEmpty(lastName))
                {
                    writer.Write("<b:Last>");
                    writer.Write(lastName);
                    writer.Write("</b:Last>");
                }
                if (!string.IsNullOrEmpty(firstName))
                {
                    writer.Write("<b:First>");
                    writer.Write(firstName);
                    writer.Write("</b:First>");
                }
                writer.Write("</b:Person>");
            }

            writer.Write("</b:NameList>");
        }

        internal static void WriteNonEmptyElement(string name, string value, TextWriter writer)
        {
            if (string.IsNullOrEmpty(value))
                return;

            writer.Write("<" + name + ">");
            writer.Write(value);
            writer.Write("</" + name + ">");
        }

        internal static void WriteRandomGuid(TextWriter writer)
        {
            writer.Write("<b:Guid>{");
            var guid = Guid.NewGuid();
            writer.Write(guid.ToString().ToUpperInvariant());
            writer.Write("}</b:Guid>");
        }
    }
}
